name: 'Push'
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: 'Build'
    strategy:
      fail-fast: false
      matrix:
        env:
          - default
          - builder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_ENV=${{ matrix.env }}
          tags: |
            ${{ secrets.DOCKER_REPO }}:${{ matrix.env }}-4.2.0
            ${{ secrets.DOCKER_REPO }}:${{ matrix.env }}-4
            ${{ secrets.DOCKER_REPO }}:${{ matrix.env }}-stable
